apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-1
  labels:
    app: app-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-1
  template:
    metadata:
      labels:
        app: app-1
    spec:
      containers:
      - name: node
        image: sckmkny/dns-performance:0.1.0
        ports:
        - name: node
          containerPort: 3000
        env:
        - name: URL
          value: "http://nginx.default.svc.cluster.local"

